### ISSUE TITLE
First issue: How to start

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#1]
Notify my using @WK-GiHu

- [stackoverflow - struggling-with-tkinter-after-method](https://stackoverflow.com/questions/59320063/struggling-with-tkinter-after-method)
- [readthedocs - kvaser#bus](https://python-can.readthedocs.io/en/master/interfaces/kvaser.html#bus)
- [CAN bus API (CANlib) ](https://www.kvaser.com/canlib-webhelp/page_canlib.html)
---

Split your code into to modules:

- [x] All `canlib` related, e.g. `canbus.py`
- [x] All GUI related could be remain as `main.py`

**Comment by JohannesAppel** [comment]
Hi @WK-GiHu, thank you.
For the `canlib`, does that include the reading functions or is it only the setUpChannel?

**Comment by WK-GiHu** [comment]
@JohannesAppel 
>For the canlib, does that include the reading functions or is it only the setUpChannel?

All from `main.py` except any `tkinter` related code.
The goal is to get your `canlib` implementation running and testing without to hassel with `tkinter`.

### Update the files in the [src](https://github.com/JohannesAppel/johannesappel-/tree/master/LogData/src) folder so i can review it.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Okay, I'll do that now and then update the `src` file.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
As the code is now in my `main.py`, it runs everything and updates my tkinter window, but it isn't instant. It takes up to 10 sec minimum for the data to update on the window and even longer depending on how long it has been running. 

To explain it better, there is some values that are constantly changing, but when I forcefully try to change a value by flipping a switch to get other data from through the Kvaser Leaf Pro, it takes a few seconds to get to that value and the code to update the tkinter window accordingly. 

I think it has to do with the 50 milliseconds wait time, everytime that the display functions is called. And adding up all those data times, it takes longer to get to the new updated values in the row. 

It sounds really confusing, so I hope this makes sense?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>then update the src file.

Waiting your notification

---

Allways start at the [Issues](https://github.com/JohannesAppel/johannesappel-/issues) page.
I open for every different issue `[New Issue]`
