### ISSUE TITLE
The desired output should be only 4 lines that updates every time new data is read.

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#10]
@WK-GiHu 
The output just continues to print out below each other. The desired output should be only 4 lines that updates every time new data is read. 

_Originally posted by @JohannesAppel in https://github.com/JohannesAppel/johannesappel-/issues/8#issuecomment-567856691_

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>The desired output should be only 4 lines that updates every time new data is read.

Replace your `tk.Text` with the following `FrameListbox`:
```
class FrameListbox(tk.Listbox):
    FRAMES_TO_SHOW = 4
    
    def __init__(self, parent, **kwargs):
        super().__init__(parent, **kwargs)

        self._count = 0
        
    def insert(self, frame):
        if self._count == FrameListbox.FRAMES_TO_SHOW:
            self.delete(0, tk.END)
            self._count = 0
        
        super().insert(tk.END, frame)
        self._count += 1
```
Change Line
https://github.com/JohannesAppel/johannesappel-/blob/ae76b9efcba3d2561eb5c23a09d59f964b4c1f30/DataLogger/src/main.py#L34

to 
```
self.frame_listbox.insert("{:<5} {}".format(frame.id, frame.data))
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Got the following error:
```
Traceback (most recent call last):
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 53, in <module>
    FrameListbox().mainloop()
TypeError: __init__() missing 1 required positional argument: 'parent'
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>`TypeError: __init__() missing 1 required positional argument: 'parent'`

The Traceback does not show the culprit, must be in Line
https://github.com/JohannesAppel/johannesappel-/blob/46c9c0ea92aa3f6bbe0c54de99d11bac0b32f8fb/DataLogger/src/main.py#L16

### Udate `main.py`

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Updated it.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

You have replaced `class App`, this was not intended
### Revert to the previous version

Insert the given `class FrameListbox` just before `class App` and replace Line
https://github.com/JohannesAppel/johannesappel-/blob/46c9c0ea92aa3f6bbe0c54de99d11bac0b32f8fb/DataLogger/src/main.py#L16

with
```
self.frame_listbox = FrameListbox(self, height=6, width=60)
```
Adjust all `self.text` with `self.frame_listbox` accordingly.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

Just now i realize that this is what `CanBus.cnt == 4` is for.
```
class FrameListbox(tk.Listbox):
    def __init__(self, parent, lines=4, **kwargs):
        super().__init__(parent, font=('Consolas', 10), **kwargs)

        self._lines_to_show = lines
        self._lines = 0
        
    def insert(self, frame):
        if self._lines == self._lines_to_show:
            self.delete(0, tk.END)
            self._lines = 0
        
        super().insert(tk.END, frame)
        self._lines += 1

class App...
    def __init__...
        ...
        self.frame_listbox = FrameListbox(self, lines=self.cbus.cnt, height=6, width=60)
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
The following error came up:
```
Traceback (most recent call last):
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 58, in <module>
    App().mainloop()
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 31, in __init__
    self.frame_listbox = FrameListbox(self, lines=self.cbus.cnt, height=6, width=60)
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 2101, in __getattr__
    return getattr(self.tk, attr)
AttributeError: '_tkinter.tkapp' object has no attribute 'cbus'
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

You have to define `self.cbus = ` first, move this Line
https://github.com/JohannesAppel/johannesappel-/blob/0de3ec35ead107cb8fafc821047b9da8572c8eae/DataLogger/src/main.py#L34

before this Line

https://github.com/JohannesAppel/johannesappel-/blob/0de3ec35ead107cb8fafc821047b9da8572c8eae/DataLogger/src/main.py#L31

**Comment by JohannesAppel** [comment]
@WK-GiHu 
```
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 49, in display
    self.frame_listbox.insert(tk.END, "%s\t%s\n" %(frame.id, frame.data))
TypeError: insert() takes 2 positional arguments but 3 were given
CanBus.stop()
EXIT, none_count:0
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>

You didn't update as requested here: https://github.com/JohannesAppel/johannesappel-/issues/10#issuecomment-567864074, the Line
https://github.com/JohannesAppel/johannesappel-/blob/0de3ec35ead107cb8fafc821047b9da8572c8eae/DataLogger/src/main.py#L49

to
```
self.frame_listbox.insert("{:<5} {}".format(frame.id, frame.data))
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Sorry, I missed it.

Everything runs, but the output is still slower than real time. `Tkinter` also flashes in a weird way. Hard to capture it in a screenshot but it is as if the data lines are displayed and taken away in the same instance. But is there just long enough to make out some of the values. Hope it makes sense.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Everything runs, but the output is still slower than real time. 

Is this also true running only `canbus.py`?
What gives the stats `frame_count <==> frame_max`, how much difference?

---

>Tkinter also flashes in a weird way. Hard to capture it in a screenshot but it is as if the data lines are displayed and taken away in the same instance. But is there just long enough to make out some of the values.

I siumulated here with `.after(1, ...`, flashing no, smooth update.
I running `linux`, i assume you are using `Windows`.
How hight is the CPU load?

Do you have any console `print(...` concurent running, this will slow down anything.

---

The only interrupt is `self.delete(...`, you could try grided `tk.Label` which does not needed to `.delete(...` just `.configure(text=frame)` but i doubt your environment isn't able to handle the load.
