### ISSUE TITLE
the output is still slower than real time

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#11]
@WK-GiHu 
Everything runs, but the output is still slower than real time. `Tkinter` also flashes in a weird way. Hard to capture it in a screenshot but it is as if the data lines are displayed and taken away in the same instance. But is there just long enough to make out some of the values. Hope it makes sense.

_Originally posted by @JohannesAppel in https://github.com/JohannesAppel/johannesappel-/issues/10#issuecomment-567929301_

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Everything runs, but the output is still slower than real time. 

Is this also true running only `canbus.py`?
What gives the stats `frame_count <==> frame_max`, how much difference?

---

>Tkinter also flashes in a weird way. Hard to capture it in a screenshot but it is as if the data lines are displayed and taken away in the same instance. But is there just long enough to make out some of the values.

I siumulated here with `.after(1, ...`, flashing no, smooth update.
I running `linux`, i assume you are using `Windows`.
How hight is the CPU load?

Do you have any console `print(...` concurent running, this will slow down anything.

---

The only interrupt is `self.delete(...`, you could try grided `tk.Label` which does not needed to `.delete(...` just `.configure(text=frame)` but i doubt your environment isn't able to handle the load.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
> Is this also true running only canbus.py?

`canbus` is also running slower than real time. 
>What gives the stats frame_count <==> frame_max, how much difference?

`max_frames` = 1000
`frame_count` = 5569

>I siumulated here with .after(1, ..., flashing no, smooth update.

I changed my `.after(10...` to a 1, it runs smoother now.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>canbus is also running slower than real time.

Then we can not expect to see *realtime* in the `tkinter` widget.

>`max_frames = 1000, frame_count = 5569`

This is a huge difference, change:
https://github.com/JohannesAppel/johannesappel-/blob/b99b1aba8136c3e543465aac0f04ba4d1c3c2017/DataLogger/src/canbus.py#L129

to
```
    time.sleep(0.005)
```
Report back how the `max_frames = 1000, frame_count = ...` ratio changes.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
`max_frames = 1000`
`frame_count = 4024`
I ran the program a few times. The `frame_count` wasn't constant. 
`frame_count = 5553`
`frame_count = 5565`
`frame_count = 5573`
`frame_count = 5560`
`frame_count = 3616`

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>`time.sleep(0.005)`

Does not change anything?
Do we count different frames?

Change the following:

1. Copy this Line
  https://github.com/JohannesAppel/johannesappel-/blob/f3b4059698cf6997470277693270a2ebbf220270/DataLogger/src/canbus.py#L63
  before Line 50
  https://github.com/JohannesAppel/johannesappel-/blob/f3b4059698cf6997470277693270a2ebbf220270/DataLogger/src/canbus.py#L50

1. Disable the whole block from Line 59 to 66
  https://github.com/JohannesAppel/johannesappel-/blob/f3b4059698cf6997470277693270a2ebbf220270/DataLogger/src/canbus.py#L59
  https://github.com/JohannesAppel/johannesappel-/blob/f3b4059698cf6997470277693270a2ebbf220270/DataLogger/src/canbus.py#L66
3. Before Line 41
  https://github.com/JohannesAppel/johannesappel-/blob/f3b4059698cf6997470277693270a2ebbf220270/DataLogger/src/canbus.py#L41
  insert
    ```
    print('Trashed frames:{}'.format(self.queue.qsize())
    ```
    The output shows the trashed frames after `cbus.stop()`.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
The `Trashed Frames` shows up empty. There is nothing displayed after it.
Here is the output:
```
canlib version: 8.30
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
CanBus.stop()
Trashed frames:
EXIT, frame_count:3996
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>The Trashed Frames shows up empty. There is nothing displayed after it.

My bad, needs a placeholder, change to
```
print('Trashed frames:{}'.format(self.queue.qsize())
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
After the changes I made it gives this error:
```
canlib version: 8.30
Traceback (most recent call last):
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\canbus.py", line 122, in <module>
    cbus = CanBus(channel=0)
TypeError: __init__() missing 1 required positional argument: 'cnt'
```
