### ISSUE TITLE
self.cnt = self.counter() 

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#18]
@JohannesAppel 

Disable the Line 23
https://github.com/JohannesAppel/johannesappel-/blob/32da8dafe2f2b22a355651fdd3d895be4503d399/DataLogger/src/canbus.py#L23

it's not used and seems not to be needed anymore.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Ok.
