### ISSUE TITLE
the code isn't running anymore. It just went directly to `Canbus.stop()`.

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#19]
@WK-GiHu 
I don't know where the problem came in now, but the code isn't running anymore. It just went directly to `Canbus.stop()`.
```
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
CanBus.stop()
Received Frame ids:[]
```

_Originally posted by @JohannesAppel in https://github.com/JohannesAppel/johannesappel-/issues/15#issuecomment-573527227_

**Comment by WK-GiHu** [comment]
@JohannesAppel 

From the given output, the `EXIT: ...` is missing.

---

Missing the following edit request from: https://github.com/JohannesAppel/johannesappel-/issues/15#issuecomment-573045143
Insert after the Line 27
https://github.com/JohannesAppel/johannesappel-/blob/32da8dafe2f2b22a355651fdd3d895be4503d399/DataLogger/src/canbus.py#L27

```
    self.trashed_count = None
```

---

Copy this Line 45
https://github.com/JohannesAppel/johannesappel-/blob/a6716128127c81f751d2fd415abfc20ca5ca6b06/DataLogger/src/main.py#L45

replace Line 142
https://github.com/JohannesAppel/johannesappel-/blob/a6716128127c81f751d2fd415abfc20ca5ca6b06/DataLogger/src/canbus.py#L142

edit it accordingly, please make it **2 Lines**, 
```
 print('EXIT, frame_count:{}, none_count:{}, trashed_count:{}'
         .format(cbus.frame_count, none_count, cbus.trashed_count)) 
```
### Run `canbus.py` to verify `class CanBus`

**Comment by JohannesAppel** [comment]
@WK-GiHu 
It still show the `CanBus.stop()` instantly. It is as if none of the data is read. 

```
canlib version: 8.30
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
CanBus.stop()
CanBus.stop()
EXIT, frame_count:None, none_count:999, trashed_count:0
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>It is as if none of the data is read.

This is probably the reason, we do `.put(e)` but never read or dispaly it.
This will also break `main::App.display()`, therefore disable Line 59.

Insert before Line 59
https://github.com/JohannesAppel/johannesappel-/blob/a6716128127c81f751d2fd415abfc20ca5ca6b06/DataLogger/src/canbus.py#L59

```
self.error = e
print('Break at unknow error: {}'.format(e))
```

To be able to show the error in the GUI part, add to `__init__`
```
self.error = None
```

---

Also missing, not relevant to this  Issue, insert before Line 27
https://github.com/JohannesAppel/johannesappel-/blob/a6716128127c81f751d2fd415abfc20ca5ca6b06/DataLogger/src/canbus.py#L27

```
self.trashed_count = None
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
This was the output after the changes.
```
canlib version: 8.30
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
Break at unknow error: unsupported operand type(s) for +=: 'NoneType' and 'int'
CanBus.stop()
CanBus.stop()
EXIT, frame_count:None, none_count:999, trashed_count:0
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

Change Line 27
https://github.com/JohannesAppel/johannesappel-/blob/a6716128127c81f751d2fd415abfc20ca5ca6b06/DataLogger/src/canbus.py#L27

to 
```
self.frame_count = 0
```

***You have mixed `self.frame_count = 0` with `self.trashed_count = None` which results in `self.frame_count = None`.***
### Doublecheck!

**Comment by JohannesAppel** [comment]
@WK-GiHu 
The `frame count` has decreased compared to the `none_count`, when the `none count` was almost zero and the `frame count` was almost the same as the `max frames`
```
canlib version: 8.30
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
CanBus.stop()
EXIT, frame_count:101, none_count:899, trashed_count:0
```
