### ISSUE TITLE
STEP 1: Get the `canlib` running without GUI

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#2]
Make `canbus.py` a Python `module` doing

```
import ...

class CanBus:
    ...

if __name__ == "__main__":
    cbus = CanBus(channel=0)
    # Read from the canbus
    while i <= 4:
        frame = cbus.read()
        show = show + ("%s\t%s\n" %(frame.id, text(frame.data)))
        print(show)
        i += 1
```

**Comment by JohannesAppel** [comment]
In the `class`, should I put all my def functions I had in the previous program code? Because it asks for a `init` function I need to create first? Or what should I add to my `class`?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>In the class, should I put all my def functions I had in the previous program code? 

Yes, **all** except the `tkinter` related ones. E.g.:
```
def tearDown(self):
    self.ch.busOff()
    self.ch.close()
```

---

>Because it asks for a init function I need to create first? 

Your `def setUpChannel` becomes th `CanBus.__init__`, e.g.:
```
def __init__(self, channel):
    self.ch = canlib.openChannel(channel, canlib.canOPEN_ACCEPT_VIRTUAL)
    print("Using channel: %s, EAN: %s" % (ChannelData(channel).channel_name,
                                          ChannelData(channel).card_upc_no)
                                                )
    self.ch.setBusOutputControl(canlib.canDRIVER_NORMAL)
    self.ch.setBusParams(canlib.canBITRATE_500K)
    self.ch.busOn()
```

**Comment by JohannesAppel** [comment]
I'll load the code up as I have it now, the class is still a bit confusing for me.

The class gives me errors and says that the `self` and `channel` is undefined, even though it is defined as parameters in the `def`. Am I understanding this wrong?

**Comment by JohannesAppel** [comment]
I changed the code as I understood that it should be, let me know if it is right.

**Comment by JohannesAppel** [comment]
I'm just uncertain about the defining a variable... After I've created the class to set up the channel.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I added the new folder with the new modules in.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>I added the new folder with the new modules in.

The new folder/modules didn't show up?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Maybe I added it at the wrong place, where should I go to add it then?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I added it at a different place now, I think you should see it now.
Sorry, I'm still quite new to this.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

### Review
https://github.com/JohannesAppel/johannesappel-/blob/3242a984dd75d6cb1074943f8a2d1a32708c8ac0/DataLogger/src/canbus.py#L20

- [x] Missing indentation, belongs to `class DataBus`, therefore indent one level
- [x] It is a `class mentod`, therefore add `...(self)`, here replace `...(ch)` with `...(self)`.
- [x] Prefix the class instance variable `ch.` with `self.ch.`.

This have to be done for the other `class method` also.

---

- [x] Move benath `if __name__ ...`
https://github.com/JohannesAppel/johannesappel-/blob/3242a984dd75d6cb1074943f8a2d1a32708c8ac0/DataLogger/src/canbus.py#L48

---
- [x] Usage unknown for know, move bothe lines benath `if __name__ ...`
https://github.com/JohannesAppel/johannesappel-/blob/3242a984dd75d6cb1074943f8a2d1a32708c8ac0/DataLogger/src/canbus.py#L50

---

- [x] Move it at the end outside of the `while ... ` block and
https://github.com/JohannesAppel/johannesappel-/blob/3242a984dd75d6cb1074943f8a2d1a32708c8ac0/DataLogger/src/canbus.py#L53

- [x] rename to

    cbus.tear_down()

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Thank you for your help so far, I really appreciate it so much. 

I've made the changes, will upload the new files shortly. I hope I understood you correctly and that I implemented everything right.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>I've made the changes, will upload the new files shortly. 

Await your notification.

>I hope I understood you correctly and that I implemented everything right.

We will see, after review.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
How do we import the `canbus.py` so that we can use it in the `main.py` module? Also how too implement it correctly when using it.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

## You didn't update the file here, can't review
- [ ] Update now

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Sorry, thought I did update it.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

### Review `canbus.py`
- [x] Sync the function name to `tear_down`
https://github.com/JohannesAppel/johannesappel-/blob/655a0ac1dce081160f36ec5e791fb6e50bd79aad/DataLogger/src/canbus.py#L20
https://github.com/JohannesAppel/johannesappel-/blob/655a0ac1dce081160f36ec5e791fb6e50bd79aad/DataLogger/src/canbus.py#L65

---

This will fail, uses `ch.read()`
https://github.com/JohannesAppel/johannesappel-/blob/655a0ac1dce081160f36ec5e791fb6e50bd79aad/DataLogger/src/canbus.py#L50

- [x] Please explain, what is `counter()` used for?
- [x] Change to `cbus.counter()`, therefore move it down beneath `cbus = CanBus(channel=0)`
  - [x]  Make it a class method, as described here: https://github.com/JohannesAppel/johannesappel-/issues/2#issuecomment-566570864

---

- [x] Run it by `python canbus.py` and verify if the output is as expected

**Comment by JohannesAppel** [comment]
@WK-GiHu 
To explain the counter function, it is used for when the amount of data lines is unknown. At the moment there is only 4 switches that can be changed so there's only 4 lines of data so that's why I set the `while i <= 4`, it like that only for testing for now. Later the `4` will be exchanged with `cnt`.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I tried to run the program, it displays everything and also the counter (which I realized  for some weird reason I needed to change the initial counter to zero to be able to get the counter to work correctly.)
But it gives an error
```
Traceback (most recent call last):
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\canbus.py", line 59, in <module>
    frame = cbus.read()
AttributeError: 'CanBus' object has no attribute 'read'
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>AttributeError: 'CanBus' object has no attribute 'read'

My bad, should read `cbus.ch.read()`, only the `Channel` could read.
You did it in `def counter` allready correct with `self.ch.read()`

---

You didn't: ***Sync the function name to tear_down*** as requested in https://github.com/JohannesAppel/johannesappel-/issues/2#issuecomment-566946989
this will throw: `AttributeError:`

---

>To explain the counter function, it is used for when the amount of data lines is unknown.

OK, could this be your **10 sec** delay?

---

>Later the 4 will be exchanged with cnt

- [x] Extend `class CanBus.__init__` to:
  ```
    def __init__(self, channel, cnt=4):`
        self.cnt = cnt
        ...
  ```
- [x] Change https://github.com/JohannesAppel/johannesappel-/blob/89b40716d57b0206f90066a454e63f2b89c3b746/DataLogger/src/canbus.py#L57 
to
  ```
  while i <= cbus.cnt:
  ```
**OR** - a function like `read_frame()` may be usefull, e.g.
```
def read_frame(self):
    frame = []
    for _ in range(self.cnt + 1):
        frame.append(self.ch.read())
    return frame
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
>OK, could this be your 10 sec delay?

Don't think so because the delay started after that function has been executed. The counter function only executes once and never again, and it executes at the start of the program only. 

>a function like read_frame() may be useful 

If I implement this, how would it impact the code I already have? And is it really necessary?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
> `for _ in range(self.cnt + 1): `

Isn't this going to cause the for loop to run 5 times? 
The counter outputs a 4 and if the loop starts at 0, doesn't that go to 5?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Isn't this going to cause the for loop to run 5 times?

Yes, it's the same as
```
    i = 0
    while i <= cbus.cnt:
        i += 1
```
## So, both are erroneous, correct it!

---

> is it really necessary?

No, it came in mind as i thought you have to read it, **frame** by **frame**.

---

To get the result from `counter()` in account change to
https://github.com/JohannesAppel/johannesappel-/blob/de3b4e0e814ab200338ae66d678e76418ce4ab0f/DataLogger/src/canbus.py#L59
```
    cbus.cnt = cbus.counter()
    print("Counter: %d" %(cbus.cnt))
```
Consider to move this into `__init__` if you have to do it at the start of the program.

---

OK, run it and verify if the 10 sec. delay happens.
Next STEP, run it in a own `Thread`.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
> To get the result from counter() in account change to

Why did I need to change this? The counter still has an output of zero after and before the change. I think the program has a problem with the `read()`.

> OK, run it and verify if the 10 sec. delay happens.

It's hard to tell if the delay happens, because there is no output. Usually if I run the code I could see how the values change when the switches are flipped, but because there is no output I can't see if it has a delay or not

> Next STEP, run it in a own Thread.

How do I run it in its' own tread?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

### You didn't update `canbus.py`, can't review

>It's hard to tell if the delay happens, because there is no output.

First it have to work at all.
See https://github.com/JohannesAppel/johannesappel-/issues/6

>How do I run it in its' own tread?

As long as it doesn't work at all this STEP have to wait.
Have you ever used the Python `Thread` module?
I think i will come up with a Pull Request as soon as `canbus.py` becomes stable.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
>Have you ever used the Python `Thread` module?

No I haven't used it, this is only my second week that I've been using Python so everything is still quite new and the only background I have is the programming I did in school and my first year of engineering, so this is kind of into the deep end for me.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

### Review `canbus.py`

- [x] Still, loops 5 times, change to `i = 1` or `while i < 4`
https://github.com/JohannesAppel/johannesappel-/blob/6af4b4af69efa8aef7aa00e276e2d6ae76898487/DataLogger/src/canbus.py#L61
https://github.com/JohannesAppel/johannesappel-/blob/6af4b4af69efa8aef7aa00e276e2d6ae76898487/DataLogger/src/canbus.py#L63

---

Your `try: ... except:`, lead to a **infinit loop**.
https://github.com/JohannesAppel/johannesappel-/blob/6af4b4af69efa8aef7aa00e276e2d6ae76898487/DataLogger/src/canbus.py#L64
Follow the rule to **only** catch the error you want to catch.
How do you re-sync if you get `canlib.canNoMsg`?

```
    frame = None
    try:
        frame = cbus.ch.read()
    except (canlib.canNoMsg):
        pass
    
    print(i)
    if frame is not None:
        print("%s\t%s\n" %(frame.id, text(frame.data)))
    i += 1
```

---

Did it work with the hard coded value `4`?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
The following output is what I get when running the code:
```
canlib version: 8.30
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
0
1
2
3
```
It isn't reading any messages. The code did work before we split up the code into to modules. Previously we only tested the `main.py`, and the code before we completely implemented the read function. This is first time testing if the read function actually works. But luckily it doesn't show errors anymore.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>But luckily it doesn't show errors anymore.

First time i run it by myself, got:
```
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    cbus = CanBus(cannel=0)
TypeError: __init__() got an unexpected keyword argument 'cannel'
```

Do you hide `Traceback`, which IDE, if any, you are using?
You should be face with the abor `Traceback` right at your first try?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Realized after I posted my comment that I didn't have the power supply on, so I couldn't connect with the switches or be able to read anything. Sorry for the inconvenience.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

OK, any output?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Yes, but it's randomly spaced:
```
canlib version: 8.30
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
0
1	['00', '1e', '84', '80']

1
2	['a6', '0b', '04', '00', '04', '00', '03', '00']

2
3	['04', '00', '03', '00', '04', '00', '03', '00']

3
4	['bc', '00', '09', '00']
```
And that's all of it, the program stopped after the 4th data line.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>And that's all of it, the program stopped after the 4th data line.

I assume, you want to read forever?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Yes, I want to be able to read real time values from the canbus, that's why the 10 sec delay bugged me. Further down the line I want to be able to store those values and compare them with earlier values to see what bits change when a switch is turned on or off. But that's for in the near future (beginning next year). 

For now I want to display updating real time values.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

Are you open to use a **producer/consumer** model with `Queue`?

**Producer**:
```
class CanBus:
    def run(self):
        while self._is_alive.is_set():
            item = None
            try:
                item = cbus.ch.read()
            except (canlib.canNoMsg):
                pass
            except:  # Break at unknow error
                self._is_alive.clear()
                continue
    
        if item is not None:
            # Possible to decode data before
            # item.data = text(item.data)
            self.queue.put(item)
```
**Consumer**:
```
def display(self):
    frame = self.cbus.get()
    self.text.insert(tk.END, "%s\t%s\n" %(frame.id, frame.data))
    self.after(10, self.display)
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I'm not familiar with the term and implementation. 
What is necessary to import? 
Can I create a new module to test this out rather?
