### ISSUE TITLE
STEP 2: GUI Part with __main__ entry point

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#3]
@JohannesAppel 

We suppose to use `Thread`, therefore we need a `__main__` entry point.
Setup the GUI using the following template:

```
import tkinter as tk

class App(tk.Tk):
    def __init__(self):
        super().__init__()
        self.protocol("WM_DELETE_WINDOW", self.quit)

        # Define any widgets
        self.text = tk.Text(self, height=6, width=60)
        ...

    def quit(self):
        # Add here any shutdown related statements
        super().quit()

if __name__ == "__main__":
    App().mainloop()
```

**Comment by JohannesAppel** [comment]
Is the code as it is basically done? Because I only want the text as a widget and no shutdown statements. 

Where does the `"__main__"` come from?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Is the code as it is basically done? Because I only want the text as a widget and no shutdown statements.

Yes, you have to add and layout additinal widgets if needed.
Also here goes the instantiation of the Channels, e.g.

    self.ch0 = CanBus(channel=0)

But build the GUI without `CanBus(...` for now.

>... no shutdown statements.

You have `self.ch0.tear_down()`, later on.

---

>Where does the "__main__" come from?

It's Python build-in, read [executing-modules-as-scripts](https://docs.python.org/3/tutorial/modules.html#executing-modules-as-scripts)

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Is there more that I need to add to the code? For example under `self.text` like the display or some of the functions that I use for the breaking up of the binary array?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Is there more that I need to add to the code? 

For now, `def display(self):`, disabled `frame = ch0.read()`:
```
def display(self):
    ...
    # frame = ch0.read()
   
```

>For example under `self.text` 

`def text(t):`, Goes to `class CanBus`

>ome of the functions that I use for the breaking up of the binary array?

Can't follow?
There is only `def counter`, can't imagin the usage for now. 
I see no GUI elements within, therefore goes to `class CanBus` 

 ---

Disable `# ...` this line for now
https://github.com/JohannesAppel/johannesappel-/blob/3242a984dd75d6cb1074943f8a2d1a32708c8ac0/DataLogger/src/main.py#L23

Missing layout statement:
https://github.com/JohannesAppel/johannesappel-/blob/3242a984dd75d6cb1074943f8a2d1a32708c8ac0/LogData/src/main.py#L83
at Line 17
https://github.com/JohannesAppel/johannesappel-/blob/3242a984dd75d6cb1074943f8a2d1a32708c8ac0/DataLogger/src/main.py#L17

    self.text.pack()

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I added the `self.text.pack` but it says `self` is undefined?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Sorry, made a stupid mistake. It's fixed now.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>I added the self.text.pack but it says self is undefined?

Have to moved to Line 17, all prefixed with `self.` belongs to a `class member` and have to be inside a `class method`, here `.__init__`

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Is everything as it needs to be? Can we start with testing it and running outputs?

Also, we're not yet writing to the tkinter window, we're only creating it as it is at the moment?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Is everything as it needs to be? 

You didn't update the files here, can't review
- [x] Update now

---

>Can we start with testing it and running outputs?

For now the GUI part should only show all widgets as needed.
- [x] Running the GUI part is OK

As soon, as the `canbus.py` test succesfull, we continue with the GUI part.



Also, we're not yet writing to the tkinter window, we're only creating it as it is at the moment?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
The window runs fine, it opens up and shows empty as expected.
