### ISSUE TITLE
It takes up to 10 sec minimum for the data to update on the window

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#5]
@JohannesAppel 

>It takes up to 10 sec minimum for the data to update on the window

We can look into this as soon the `canbus.py` module is ready for testing.

**Comment by JohannesAppel** [comment]
Is the `canbus.py` ready for testing yet?

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Is the `canbus.py` ready for testing?

**Comment by WK-GiHu** [comment]
@JohannesAppel 
 Extend `max_frames` as much to the time you get the 10 sec delay.
 Maybe `x 1000` or `x 10000` if the `none_count` increases the culprit is at the `CAN BUS`.

 Or use `Timer` to stop after a given time
  ```
    # Terminate after 10 * 60 seconds
    threading.Timer(10 * 60, cbus.stop).start()
    cbus.start()

    none_count = 0
    while cbus.is_alive():
        time.sleep(0.1)
        frame = cbus.get()
        if frame is None:
            none_count +=1
        else:
            print(frame)
       
    # Allready stoped from Timer 
    # cbus.stop()
    print('EXIT, none_count:{}'.format(none_count))
  ```
