### ISSUE TITLE
The counter still has an output of zero

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#6]
@WK-GiHu 
> To get the result from counter() in account change to

Why did I need to change this? The counter still has an output of zero after and before the change. I think the program has a problem with the `read()`.

_Originally posted by @JohannesAppel in https://github.com/JohannesAppel/johannesappel-/issues/2#issuecomment-567358403_

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>Why did I need to change this? 

You have to decide:
- [ ] I want to use the result of `counter()` => `self.cnt = counter()`
  We have to find, **why** the result is `0`

- [x] I want **NOT** to use the result of `counter()` now
  We skip, the usage of `counter()` and continue with hard coded value `self.cnt = 4`
  Therefor, disabel the two lines:
  ```
    # cnt = cbus.counter()
    # print("Counter: %d" %(cnt))
  ```
---

>The counter still has an output of zero after and before the change. I think the program has a problem with the read().
### Please confirm
- [ ] `counter()` has not worked ever, means allways shows `0`
- [x] `counter()` worked in my initial version

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I think for now we can hard code it. We can later come back to this after we can read properly and output the data in `tkinter`.

**Comment by WK-GiHu** [comment]
Close for now, continue with hard coded value `4`

The `try: ... except:` hides all errors, change to
```
        except canlib.canNoMsg as e:
            print('counter:{}'.format(e))
            pass
        except canlib.canError as e:
            print('counter:{}'.format(e))
            pass
        return cnt
```
