### ISSUE TITLE
STEP 2.2 GUI Consumer part `def display(self)`

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#8]
@JohannesAppel 

**Consumer**:

```
from canbus import CanBus

class App(tk.Tk):
    def __init__(self):
        ...

        self.none_count = 0
        self.cbus = CanBus(channel=0)
        self.cbus.start()
        self.after(10, self.display)

    def quit(self):
        # Add here any shutdown related statements
        self.cbus.stop()
        self.cbus.tearDownChannel()
        print('EXIT, none_count:{}'.format(self.none_count))
        super().quit()

    def display(self):
        if self.cbus.is_alive():
            frame = self.cbus.get()
            if frame is not None:
                self.text.insert(tk.END, "%s\t%s\n" %(frame.id, frame.data))
            else:
                self.none_count += 1

            self.after(10, self.display)

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I implemented the code into my `main` module. 
I added a `self.` in front of this line since it gave an error otherwise. 
```
cbus.start()
```

And then there's a problem with the print function in the main. 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 34, in display
    self.text.insert(tk.END, "%s\t%s\n" %(frame.id, frame.data))
AttributeError: 'str' object has no attribute 'id'
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 
Can't follow your comment: https://github.com/JohannesAppel/johannesappel-/issues/7#issuecomment-567850087 ?

>tkinter outputs data now after the changes, 

Which **changes**?
Is the `AttributeError: 'str' object has no attribute 'id'` gone?

>but the tkinter app doesn't update the vlaues a of yet. 
>It just appends the values at the bottom of the previous print of values.

Can't imagin this ?
Maybe a screenshoot?

**Comment by JohannesAppel** [comment]
![Screenshot (14)](https://user-images.githubusercontent.com/58848423/71244744-ddc53700-231b-11ea-8c67-2061a2d350bb.png)

@WK-GiHu 
The output just continues to print out below each other. The desired output should be only 4 lines that updates every time new data is read. 

>Is the AttributeError: 'str' object has no attribute 'id' gone?

Yes it seems like it is gone now. Also a bit suspicious about how that could've happened.
